// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/AddRecordRequest
type AddRecordRequest struct {
	Identifier     string   `json:"identifier"`
	MetadataPrefix string   `json:"metadata_prefix"`
	Metadata       string   `json:"metadata"`
	SetSpecs       []string `json:"set_specs"`
}

// GetIdentifier returns the value of Identifier.
func (s *AddRecordRequest) GetIdentifier() string {
	return s.Identifier
}

// GetMetadataPrefix returns the value of MetadataPrefix.
func (s *AddRecordRequest) GetMetadataPrefix() string {
	return s.MetadataPrefix
}

// GetMetadata returns the value of Metadata.
func (s *AddRecordRequest) GetMetadata() string {
	return s.Metadata
}

// GetSetSpecs returns the value of SetSpecs.
func (s *AddRecordRequest) GetSetSpecs() []string {
	return s.SetSpecs
}

// SetIdentifier sets the value of Identifier.
func (s *AddRecordRequest) SetIdentifier(val string) {
	s.Identifier = val
}

// SetMetadataPrefix sets the value of MetadataPrefix.
func (s *AddRecordRequest) SetMetadataPrefix(val string) {
	s.MetadataPrefix = val
}

// SetMetadata sets the value of Metadata.
func (s *AddRecordRequest) SetMetadata(val string) {
	s.Metadata = val
}

// SetSetSpecs sets the value of SetSpecs.
func (s *AddRecordRequest) SetSetSpecs(val []string) {
	s.SetSpecs = val
}

// Ref: #/components/schemas/AddRecordResponse
type AddRecordResponse struct {
	Identifier OptString `json:"identifier"`
}

// GetIdentifier returns the value of Identifier.
func (s *AddRecordResponse) GetIdentifier() OptString {
	return s.Identifier
}

// SetIdentifier sets the value of Identifier.
func (s *AddRecordResponse) SetIdentifier(val OptString) {
	s.Identifier = val
}

// Represents error object.
// Ref: #/components/schemas/Error
type Error struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int64 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int64) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
