// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ugent-library/oai-service/ent/metadata"
	"github.com/ugent-library/oai-service/ent/metadataformat"
	"github.com/ugent-library/oai-service/ent/predicate"
	"github.com/ugent-library/oai-service/ent/record"
)

// MetadataUpdate is the builder for updating Metadata entities.
type MetadataUpdate struct {
	config
	hooks    []Hook
	mutation *MetadataMutation
}

// Where appends a list predicates to the MetadataUpdate builder.
func (mu *MetadataUpdate) Where(ps ...predicate.Metadata) *MetadataUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetRecordID sets the "record_id" field.
func (mu *MetadataUpdate) SetRecordID(i int64) *MetadataUpdate {
	mu.mutation.SetRecordID(i)
	return mu
}

// SetMetadataFormatID sets the "metadata_format_id" field.
func (mu *MetadataUpdate) SetMetadataFormatID(i int64) *MetadataUpdate {
	mu.mutation.SetMetadataFormatID(i)
	return mu
}

// SetXML sets the "xml" field.
func (mu *MetadataUpdate) SetXML(s string) *MetadataUpdate {
	mu.mutation.SetXML(s)
	return mu
}

// SetDatestamp sets the "datestamp" field.
func (mu *MetadataUpdate) SetDatestamp(t time.Time) *MetadataUpdate {
	mu.mutation.SetDatestamp(t)
	return mu
}

// SetNillableDatestamp sets the "datestamp" field if the given value is not nil.
func (mu *MetadataUpdate) SetNillableDatestamp(t *time.Time) *MetadataUpdate {
	if t != nil {
		mu.SetDatestamp(*t)
	}
	return mu
}

// SetRecord sets the "record" edge to the Record entity.
func (mu *MetadataUpdate) SetRecord(r *Record) *MetadataUpdate {
	return mu.SetRecordID(r.ID)
}

// SetMetadataFormat sets the "metadata_format" edge to the MetadataFormat entity.
func (mu *MetadataUpdate) SetMetadataFormat(m *MetadataFormat) *MetadataUpdate {
	return mu.SetMetadataFormatID(m.ID)
}

// Mutation returns the MetadataMutation object of the builder.
func (mu *MetadataUpdate) Mutation() *MetadataMutation {
	return mu.mutation
}

// ClearRecord clears the "record" edge to the Record entity.
func (mu *MetadataUpdate) ClearRecord() *MetadataUpdate {
	mu.mutation.ClearRecord()
	return mu
}

// ClearMetadataFormat clears the "metadata_format" edge to the MetadataFormat entity.
func (mu *MetadataUpdate) ClearMetadataFormat() *MetadataUpdate {
	mu.mutation.ClearMetadataFormat()
	return mu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MetadataUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MetadataUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MetadataUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MetadataUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MetadataUpdate) check() error {
	if _, ok := mu.mutation.RecordID(); mu.mutation.RecordCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Metadata.record"`)
	}
	if _, ok := mu.mutation.MetadataFormatID(); mu.mutation.MetadataFormatCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Metadata.metadata_format"`)
	}
	return nil
}

func (mu *MetadataUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(metadata.Table, metadata.Columns, sqlgraph.NewFieldSpec(metadata.FieldID, field.TypeInt64))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.XML(); ok {
		_spec.SetField(metadata.FieldXML, field.TypeString, value)
	}
	if value, ok := mu.mutation.Datestamp(); ok {
		_spec.SetField(metadata.FieldDatestamp, field.TypeTime, value)
	}
	if mu.mutation.RecordCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   metadata.RecordTable,
			Columns: []string{metadata.RecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(record.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   metadata.RecordTable,
			Columns: []string{metadata.RecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(record.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.MetadataFormatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   metadata.MetadataFormatTable,
			Columns: []string{metadata.MetadataFormatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(metadataformat.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.MetadataFormatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   metadata.MetadataFormatTable,
			Columns: []string{metadata.MetadataFormatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(metadataformat.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{metadata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MetadataUpdateOne is the builder for updating a single Metadata entity.
type MetadataUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MetadataMutation
}

// SetRecordID sets the "record_id" field.
func (muo *MetadataUpdateOne) SetRecordID(i int64) *MetadataUpdateOne {
	muo.mutation.SetRecordID(i)
	return muo
}

// SetMetadataFormatID sets the "metadata_format_id" field.
func (muo *MetadataUpdateOne) SetMetadataFormatID(i int64) *MetadataUpdateOne {
	muo.mutation.SetMetadataFormatID(i)
	return muo
}

// SetXML sets the "xml" field.
func (muo *MetadataUpdateOne) SetXML(s string) *MetadataUpdateOne {
	muo.mutation.SetXML(s)
	return muo
}

// SetDatestamp sets the "datestamp" field.
func (muo *MetadataUpdateOne) SetDatestamp(t time.Time) *MetadataUpdateOne {
	muo.mutation.SetDatestamp(t)
	return muo
}

// SetNillableDatestamp sets the "datestamp" field if the given value is not nil.
func (muo *MetadataUpdateOne) SetNillableDatestamp(t *time.Time) *MetadataUpdateOne {
	if t != nil {
		muo.SetDatestamp(*t)
	}
	return muo
}

// SetRecord sets the "record" edge to the Record entity.
func (muo *MetadataUpdateOne) SetRecord(r *Record) *MetadataUpdateOne {
	return muo.SetRecordID(r.ID)
}

// SetMetadataFormat sets the "metadata_format" edge to the MetadataFormat entity.
func (muo *MetadataUpdateOne) SetMetadataFormat(m *MetadataFormat) *MetadataUpdateOne {
	return muo.SetMetadataFormatID(m.ID)
}

// Mutation returns the MetadataMutation object of the builder.
func (muo *MetadataUpdateOne) Mutation() *MetadataMutation {
	return muo.mutation
}

// ClearRecord clears the "record" edge to the Record entity.
func (muo *MetadataUpdateOne) ClearRecord() *MetadataUpdateOne {
	muo.mutation.ClearRecord()
	return muo
}

// ClearMetadataFormat clears the "metadata_format" edge to the MetadataFormat entity.
func (muo *MetadataUpdateOne) ClearMetadataFormat() *MetadataUpdateOne {
	muo.mutation.ClearMetadataFormat()
	return muo
}

// Where appends a list predicates to the MetadataUpdate builder.
func (muo *MetadataUpdateOne) Where(ps ...predicate.Metadata) *MetadataUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MetadataUpdateOne) Select(field string, fields ...string) *MetadataUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Metadata entity.
func (muo *MetadataUpdateOne) Save(ctx context.Context) (*Metadata, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MetadataUpdateOne) SaveX(ctx context.Context) *Metadata {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MetadataUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MetadataUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MetadataUpdateOne) check() error {
	if _, ok := muo.mutation.RecordID(); muo.mutation.RecordCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Metadata.record"`)
	}
	if _, ok := muo.mutation.MetadataFormatID(); muo.mutation.MetadataFormatCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Metadata.metadata_format"`)
	}
	return nil
}

func (muo *MetadataUpdateOne) sqlSave(ctx context.Context) (_node *Metadata, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(metadata.Table, metadata.Columns, sqlgraph.NewFieldSpec(metadata.FieldID, field.TypeInt64))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Metadata.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, metadata.FieldID)
		for _, f := range fields {
			if !metadata.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != metadata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.XML(); ok {
		_spec.SetField(metadata.FieldXML, field.TypeString, value)
	}
	if value, ok := muo.mutation.Datestamp(); ok {
		_spec.SetField(metadata.FieldDatestamp, field.TypeTime, value)
	}
	if muo.mutation.RecordCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   metadata.RecordTable,
			Columns: []string{metadata.RecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(record.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   metadata.RecordTable,
			Columns: []string{metadata.RecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(record.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.MetadataFormatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   metadata.MetadataFormatTable,
			Columns: []string{metadata.MetadataFormatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(metadataformat.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.MetadataFormatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   metadata.MetadataFormatTable,
			Columns: []string{metadata.MetadataFormatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(metadataformat.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Metadata{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{metadata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
