// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ugent-library/oai-service/ent/item"
	"github.com/ugent-library/oai-service/ent/metadataformat"
	"github.com/ugent-library/oai-service/ent/predicate"
	"github.com/ugent-library/oai-service/ent/record"
)

// RecordUpdate is the builder for updating Record entities.
type RecordUpdate struct {
	config
	hooks    []Hook
	mutation *RecordMutation
}

// Where appends a list predicates to the RecordUpdate builder.
func (ru *RecordUpdate) Where(ps ...predicate.Record) *RecordUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetMetadataFormatID sets the "metadata_format_id" field.
func (ru *RecordUpdate) SetMetadataFormatID(s string) *RecordUpdate {
	ru.mutation.SetMetadataFormatID(s)
	return ru
}

// SetItemID sets the "item_id" field.
func (ru *RecordUpdate) SetItemID(s string) *RecordUpdate {
	ru.mutation.SetItemID(s)
	return ru
}

// SetMetadata sets the "metadata" field.
func (ru *RecordUpdate) SetMetadata(s string) *RecordUpdate {
	ru.mutation.SetMetadata(s)
	return ru
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (ru *RecordUpdate) SetNillableMetadata(s *string) *RecordUpdate {
	if s != nil {
		ru.SetMetadata(*s)
	}
	return ru
}

// ClearMetadata clears the value of the "metadata" field.
func (ru *RecordUpdate) ClearMetadata() *RecordUpdate {
	ru.mutation.ClearMetadata()
	return ru
}

// SetDatestamp sets the "datestamp" field.
func (ru *RecordUpdate) SetDatestamp(t time.Time) *RecordUpdate {
	ru.mutation.SetDatestamp(t)
	return ru
}

// SetNillableDatestamp sets the "datestamp" field if the given value is not nil.
func (ru *RecordUpdate) SetNillableDatestamp(t *time.Time) *RecordUpdate {
	if t != nil {
		ru.SetDatestamp(*t)
	}
	return ru
}

// SetMetadataFormat sets the "metadata_format" edge to the MetadataFormat entity.
func (ru *RecordUpdate) SetMetadataFormat(m *MetadataFormat) *RecordUpdate {
	return ru.SetMetadataFormatID(m.ID)
}

// SetItem sets the "item" edge to the Item entity.
func (ru *RecordUpdate) SetItem(i *Item) *RecordUpdate {
	return ru.SetItemID(i.ID)
}

// Mutation returns the RecordMutation object of the builder.
func (ru *RecordUpdate) Mutation() *RecordMutation {
	return ru.mutation
}

// ClearMetadataFormat clears the "metadata_format" edge to the MetadataFormat entity.
func (ru *RecordUpdate) ClearMetadataFormat() *RecordUpdate {
	ru.mutation.ClearMetadataFormat()
	return ru
}

// ClearItem clears the "item" edge to the Item entity.
func (ru *RecordUpdate) ClearItem() *RecordUpdate {
	ru.mutation.ClearItem()
	return ru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RecordUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RecordUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RecordUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *RecordUpdate) check() error {
	if _, ok := ru.mutation.MetadataFormatID(); ru.mutation.MetadataFormatCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Record.metadata_format"`)
	}
	if _, ok := ru.mutation.ItemID(); ru.mutation.ItemCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Record.item"`)
	}
	return nil
}

func (ru *RecordUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(record.Table, record.Columns, sqlgraph.NewFieldSpec(record.FieldID, field.TypeInt64))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.Metadata(); ok {
		_spec.SetField(record.FieldMetadata, field.TypeString, value)
	}
	if ru.mutation.MetadataCleared() {
		_spec.ClearField(record.FieldMetadata, field.TypeString)
	}
	if value, ok := ru.mutation.Datestamp(); ok {
		_spec.SetField(record.FieldDatestamp, field.TypeTime, value)
	}
	if ru.mutation.MetadataFormatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   record.MetadataFormatTable,
			Columns: []string{record.MetadataFormatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(metadataformat.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.MetadataFormatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   record.MetadataFormatTable,
			Columns: []string{record.MetadataFormatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(metadataformat.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   record.ItemTable,
			Columns: []string{record.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   record.ItemTable,
			Columns: []string{record.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{record.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RecordUpdateOne is the builder for updating a single Record entity.
type RecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecordMutation
}

// SetMetadataFormatID sets the "metadata_format_id" field.
func (ruo *RecordUpdateOne) SetMetadataFormatID(s string) *RecordUpdateOne {
	ruo.mutation.SetMetadataFormatID(s)
	return ruo
}

// SetItemID sets the "item_id" field.
func (ruo *RecordUpdateOne) SetItemID(s string) *RecordUpdateOne {
	ruo.mutation.SetItemID(s)
	return ruo
}

// SetMetadata sets the "metadata" field.
func (ruo *RecordUpdateOne) SetMetadata(s string) *RecordUpdateOne {
	ruo.mutation.SetMetadata(s)
	return ruo
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (ruo *RecordUpdateOne) SetNillableMetadata(s *string) *RecordUpdateOne {
	if s != nil {
		ruo.SetMetadata(*s)
	}
	return ruo
}

// ClearMetadata clears the value of the "metadata" field.
func (ruo *RecordUpdateOne) ClearMetadata() *RecordUpdateOne {
	ruo.mutation.ClearMetadata()
	return ruo
}

// SetDatestamp sets the "datestamp" field.
func (ruo *RecordUpdateOne) SetDatestamp(t time.Time) *RecordUpdateOne {
	ruo.mutation.SetDatestamp(t)
	return ruo
}

// SetNillableDatestamp sets the "datestamp" field if the given value is not nil.
func (ruo *RecordUpdateOne) SetNillableDatestamp(t *time.Time) *RecordUpdateOne {
	if t != nil {
		ruo.SetDatestamp(*t)
	}
	return ruo
}

// SetMetadataFormat sets the "metadata_format" edge to the MetadataFormat entity.
func (ruo *RecordUpdateOne) SetMetadataFormat(m *MetadataFormat) *RecordUpdateOne {
	return ruo.SetMetadataFormatID(m.ID)
}

// SetItem sets the "item" edge to the Item entity.
func (ruo *RecordUpdateOne) SetItem(i *Item) *RecordUpdateOne {
	return ruo.SetItemID(i.ID)
}

// Mutation returns the RecordMutation object of the builder.
func (ruo *RecordUpdateOne) Mutation() *RecordMutation {
	return ruo.mutation
}

// ClearMetadataFormat clears the "metadata_format" edge to the MetadataFormat entity.
func (ruo *RecordUpdateOne) ClearMetadataFormat() *RecordUpdateOne {
	ruo.mutation.ClearMetadataFormat()
	return ruo
}

// ClearItem clears the "item" edge to the Item entity.
func (ruo *RecordUpdateOne) ClearItem() *RecordUpdateOne {
	ruo.mutation.ClearItem()
	return ruo
}

// Where appends a list predicates to the RecordUpdate builder.
func (ruo *RecordUpdateOne) Where(ps ...predicate.Record) *RecordUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RecordUpdateOne) Select(field string, fields ...string) *RecordUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Record entity.
func (ruo *RecordUpdateOne) Save(ctx context.Context) (*Record, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RecordUpdateOne) SaveX(ctx context.Context) *Record {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RecordUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RecordUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *RecordUpdateOne) check() error {
	if _, ok := ruo.mutation.MetadataFormatID(); ruo.mutation.MetadataFormatCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Record.metadata_format"`)
	}
	if _, ok := ruo.mutation.ItemID(); ruo.mutation.ItemCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Record.item"`)
	}
	return nil
}

func (ruo *RecordUpdateOne) sqlSave(ctx context.Context) (_node *Record, err error) {
	if err := ruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(record.Table, record.Columns, sqlgraph.NewFieldSpec(record.FieldID, field.TypeInt64))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Record.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, record.FieldID)
		for _, f := range fields {
			if !record.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != record.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.Metadata(); ok {
		_spec.SetField(record.FieldMetadata, field.TypeString, value)
	}
	if ruo.mutation.MetadataCleared() {
		_spec.ClearField(record.FieldMetadata, field.TypeString)
	}
	if value, ok := ruo.mutation.Datestamp(); ok {
		_spec.SetField(record.FieldDatestamp, field.TypeTime, value)
	}
	if ruo.mutation.MetadataFormatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   record.MetadataFormatTable,
			Columns: []string{record.MetadataFormatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(metadataformat.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.MetadataFormatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   record.MetadataFormatTable,
			Columns: []string{record.MetadataFormatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(metadataformat.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   record.ItemTable,
			Columns: []string{record.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   record.ItemTable,
			Columns: []string{record.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Record{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{record.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
