// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ugent-library/oai-service/ent/record"
	"github.com/ugent-library/oai-service/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	recordFields := schema.Record{}.Fields()
	_ = recordFields
	// recordDescDeleted is the schema descriptor for deleted field.
	recordDescDeleted := recordFields[4].Descriptor()
	// record.DefaultDeleted holds the default value on creation for the deleted field.
	record.DefaultDeleted = recordDescDeleted.Default.(bool)
	// recordDescDatestamp is the schema descriptor for datestamp field.
	recordDescDatestamp := recordFields[5].Descriptor()
	// record.DefaultDatestamp holds the default value on creation for the datestamp field.
	record.DefaultDatestamp = recordDescDatestamp.Default.(func() time.Time)
	// record.UpdateDefaultDatestamp holds the default value on update for the datestamp field.
	record.UpdateDefaultDatestamp = recordDescDatestamp.UpdateDefault.(func() time.Time)
}
