// Code generated by ent, DO NOT EDIT.

package metadata

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the metadata type in the database.
	Label = "metadata"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRecordID holds the string denoting the record_id field in the database.
	FieldRecordID = "record_id"
	// FieldMetadataFormatID holds the string denoting the metadata_format_id field in the database.
	FieldMetadataFormatID = "metadata_format_id"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldDatestamp holds the string denoting the datestamp field in the database.
	FieldDatestamp = "datestamp"
	// EdgeRecord holds the string denoting the record edge name in mutations.
	EdgeRecord = "record"
	// EdgeMetadataFormat holds the string denoting the metadata_format edge name in mutations.
	EdgeMetadataFormat = "metadata_format"
	// Table holds the table name of the metadata in the database.
	Table = "metadata"
	// RecordTable is the table that holds the record relation/edge.
	RecordTable = "metadata"
	// RecordInverseTable is the table name for the Record entity.
	// It exists in this package in order to avoid circular dependency with the "record" package.
	RecordInverseTable = "records"
	// RecordColumn is the table column denoting the record relation/edge.
	RecordColumn = "record_id"
	// MetadataFormatTable is the table that holds the metadata_format relation/edge.
	MetadataFormatTable = "metadata"
	// MetadataFormatInverseTable is the table name for the MetadataFormat entity.
	// It exists in this package in order to avoid circular dependency with the "metadataformat" package.
	MetadataFormatInverseTable = "metadata_formats"
	// MetadataFormatColumn is the table column denoting the metadata_format relation/edge.
	MetadataFormatColumn = "metadata_format_id"
)

// Columns holds all SQL columns for metadata fields.
var Columns = []string{
	FieldID,
	FieldRecordID,
	FieldMetadataFormatID,
	FieldMetadata,
	FieldDatestamp,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDatestamp holds the default value on creation for the "datestamp" field.
	DefaultDatestamp func() time.Time
	// UpdateDefaultDatestamp holds the default value on update for the "datestamp" field.
	UpdateDefaultDatestamp func() time.Time
)

// OrderOption defines the ordering options for the Metadata queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRecordID orders the results by the record_id field.
func ByRecordID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordID, opts...).ToFunc()
}

// ByMetadataFormatID orders the results by the metadata_format_id field.
func ByMetadataFormatID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataFormatID, opts...).ToFunc()
}

// ByMetadata orders the results by the metadata field.
func ByMetadata(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadata, opts...).ToFunc()
}

// ByDatestamp orders the results by the datestamp field.
func ByDatestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDatestamp, opts...).ToFunc()
}

// ByRecordField orders the results by record field.
func ByRecordField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecordStep(), sql.OrderByField(field, opts...))
	}
}

// ByMetadataFormatField orders the results by metadata_format field.
func ByMetadataFormatField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMetadataFormatStep(), sql.OrderByField(field, opts...))
	}
}
func newRecordStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecordInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RecordTable, RecordColumn),
	)
}
func newMetadataFormatStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MetadataFormatInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MetadataFormatTable, MetadataFormatColumn),
	)
}
