// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// MetadataFormat is the predicate function for metadataformat builders.
type MetadataFormat func(*sql.Selector)

// Record is the predicate function for record builders.
type Record func(*sql.Selector)

// Set is the predicate function for set builders.
type Set func(*sql.Selector)
